# /etc/X11/xorg.conf.d/19-nvidia.conf
Section "Device"
    Identifier   "Nvidia Card"
    Driver       "nvidia"
    Option       "NoLogo"             "1"
    Option       "RenderAccel"        "1"
    Option       "TripleBuffer"       "true"
    Option       "MigrationHeuristic" "greedy"
    Option       "Coolbits"           "__GAMING_NVIDIA_COOLBITS__"
EndSection
